services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile.dev
      args:
        PORT: 8000
        ORIGINS: ""
        NODE_ENV: "development"
        DATABASE_URL_PROD: postgresql://user:veryStrongPassword@db:5432/dev-db
        DATABASE_URL_TEST: postgresql://user:veryStrongPassword@db:5432/dev-db
        DATABASE_URL_DEV: postgresql://user:veryStrongPassword@db:5432/dev-db
    container_name: app-dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:veryStrongPassword@db:5432/dev-db
      NODE_ENV: developement
      PORT: 8000

  db:
    image: postgres:16-alpine
    container_name: postgres-dev-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: veryStrongPassword
      POSTGRES_DB: dev-db
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dev-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
